### ISSUE TITLE
seed-deck.js no bueno

### ISSUE THREAD

**Issue by sbenthall** [yrevocnu/psychedelic-glass-bead-game#19]
`$ node bin/seed-deck.js`

Error: 
```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/sb/projects/yrevocnu/psychedelic-glass-bead-game/lib/models/Deck' imported from /home/sb/projects/yrevocnu/psychedelic-glass-bead-game/bin/seed-deck.js
    at finalizeResolution (internal/modules/esm/resolve.js:270:11)
    at moduleResolve (internal/modules/esm/resolve.js:667:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:778:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

No docs for using this script! What is happening?

**Comment by benheller** [comment]
This has been resolved in 87bd9b9
