### ISSUE TITLE
Unhandled promise exception

### ISSUE THREAD

**Issue by sbenthall** [yrevocnu/psychedelic-glass-bead-game#2]
```
$ yarn seed:db
yarn run v1.21.1
$ node --experimental-modules --es-module-specifier-resolution=node ./bin/seed-db.js
(node:22080) ExperimentalWarning: The ESM module loader is experimental.
(node:22104) ExperimentalWarning: The ESM module loader is experimental.
(node:22104) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at new MongooseServerSelectionError (/home/sb/projects/yrevocnu/psychedelic-glass-bead-game/node_modules/mongoose/lib/error/serverSelection.js:22:11)
    at NativeConnection.Connection.openUri (/home/sb/projects/yrevocnu/psychedelic-glass-bead-game/node_modules/mongoose/lib/connection.js:823:32)
    at Mongoose.connect (/home/sb/projects/yrevocnu/psychedelic-glass-bead-game/node_modules/mongoose/lib/index.js:333:15)
    at file:///home/sb/projects/yrevocnu/psychedelic-glass-bead-game/lib/services/mongoose.js:4:10
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:176:24)
(node:22104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22155) ExperimentalWarning: The ESM module loader is experimental.
(node:22155) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at new MongooseServerSelectionError (/home/sb/projects/yrevocnu/psychedelic-glass-bead-game/node_modules/mongoose/lib/error/serverSelection.js:22:11)
    at NativeConnection.Connection.openUri (/home/sb/projects/yrevocnu/psychedelic-glass-bead-game/node_modules/mongoose/lib/connection.js:823:32)
    at Mongoose.connect (/home/sb/projects/yrevocnu/psychedelic-glass-bead-game/node_modules/mongoose/lib/index.js:333:15)
    at file:///home/sb/projects/yrevocnu/psychedelic-glass-bead-game/lib/services/mongoose.js:4:10
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:176:24)
(node:22155) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22155) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by benheller** [comment]
This error means that the seed script cannot connect to a database at `127.0.0.1:27017`. I can/will update that script so that this throws a cleaner, more descriptive error message. Can you confirm that you're able to connect to your local Mongo database, using a free app like https://www.mongodb.com/products/compass?

**Comment by sbenthall** [comment]
```
$ mongo
MongoDB shell version v4.2.5
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
2020-04-21T13:52:05.660-0400 E  QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:341:17
@(connect):2:6
2020-04-21T13:52:05.662-0400 F  -        [main] exception: connect failed
2020-04-21T13:52:05.662-0400 E  -        [main] exiting with code 1
```

**Comment by benheller** [comment]
That indicates that you indeed don't have Mongo running. After installing Mongo, did you start it as a system service? As per the instruction here https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/?

> sudo systemctl start mongod

**Comment by sbenthall** [comment]
Ah, thank you. Starting mongo with that command worked.

I suppose I have to run that every time I reboot?

**Comment by benheller** [comment]
`systemctl` will register Mongo as a system service, will will automatically launch at startup. You might want to read up about Linux system services, as they can be pretty handy: https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units
